package vista;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import modelo.Conexion;

public class FrmHome extends javax.swing.JFrame {

 /**
  * Creates new form FrmHome
  *
  * @param id
  */
 int id_global;
 public FrmHome(int id) {
  initComponents();
  this.setLocationRelativeTo(null);

  actualizarBienvenida(id);
  actualizarEstadisticas(id);
  
  id_global = id;
 }
 
 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel1 = new javax.swing.JPanel();
  lblBienvenida = new javax.swing.JLabel();
  jPanel2 = new javax.swing.JPanel();
  jLabel1 = new javax.swing.JLabel();
  lblCarnet = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  lblNombreCompleto = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();
  lblCarrera = new javax.swing.JLabel();
  jLabel4 = new javax.swing.JLabel();
  lblEmail = new javax.swing.JLabel();
  jPanel3 = new javax.swing.JPanel();
  lblNotas = new javax.swing.JLabel();
  jPanel4 = new javax.swing.JPanel();
  lblContactos = new javax.swing.JLabel();
  jLabel5 = new javax.swing.JLabel();
  jLabel6 = new javax.swing.JLabel();
  btnContactos = new javax.swing.JButton();
  btnNotas = new javax.swing.JButton();
  jMenuBar1 = new javax.swing.JMenuBar();
  menuAgregarContacto = new javax.swing.JMenu();
  jMenuItem1 = new javax.swing.JMenuItem();
  menuVerContacto = new javax.swing.JMenuItem();
  jMenu2 = new javax.swing.JMenu();
  menuAgregarNotas = new javax.swing.JMenuItem();
  menuVernotas = new javax.swing.JMenuItem();
  MenuCerrar = new javax.swing.JMenu();
  MenuSesion = new javax.swing.JMenuItem();
  MenuSalir = new javax.swing.JMenuItem();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Administración de contactos y notas");
  setResizable(false);

  jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

  lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addGap(18, 18, 18)
    .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sus datos"));

  jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
  jLabel1.setText("Carnet:");

  lblCarnet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
  lblCarnet.setText("00-0000-0000");

  jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
  jLabel2.setText("Nombre completo:");

  lblNombreCompleto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
  lblNombreCompleto.setText("Nombre Nombre Apellido Apellido");

  jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
  jLabel3.setText("Carrera:");

  lblCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
  lblCarrera.setText("Carrera");

  jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
  jLabel4.setText("Email:");

  lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
  lblEmail.setText("correo_electronico@utec.com");

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(20, 20, 20)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(lblNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(jLabel1)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(lblCarnet))
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addComponent(jLabel3)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(lblCarrera)
      .addGap(64, 64, 64)
      .addComponent(jLabel4)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  jPanel2Layout.setVerticalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(15, 15, 15)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel1)
     .addComponent(lblCarnet))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel2)
     .addComponent(lblNombreCompleto))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel3)
     .addComponent(lblCarrera)
     .addComponent(jLabel4)
     .addComponent(lblEmail))
    .addContainerGap(15, Short.MAX_VALUE))
  );

  jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Notas"));

  lblNotas.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
  lblNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  lblNotas.setText("00");

  javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
  jPanel3.setLayout(jPanel3Layout);
  jPanel3Layout.setHorizontalGroup(
   jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel3Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(lblNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
    .addContainerGap())
  );
  jPanel3Layout.setVerticalGroup(
   jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(lblNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
    .addContainerGap())
  );

  jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contactos"));

  lblContactos.setFont(new java.awt.Font("Consolas", 1, 70)); // NOI18N
  lblContactos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  lblContactos.setText("00");

  javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
  jPanel4.setLayout(jPanel4Layout);
  jPanel4Layout.setHorizontalGroup(
   jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(lblContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
    .addContainerGap())
  );
  jPanel4Layout.setVerticalGroup(
   jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel4Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(lblContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
    .addContainerGap())
  );

  jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

  jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

  btnContactos.setText("Mis contactos");
  btnContactos.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnContactosActionPerformed(evt);
   }
  });

  btnNotas.setText("Mis notas");
  btnNotas.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnNotasActionPerformed(evt);
   }
  });

  jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
  jMenuBar1.setBorder(null);
  jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

  menuAgregarContacto.setText("Contactos");

  jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
  jMenuItem1.setText("Agregar Contactos");
  jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem1ActionPerformed(evt);
   }
  });
  menuAgregarContacto.add(jMenuItem1);

  menuVerContacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
  menuVerContacto.setText("Ver Contacos");
  menuVerContacto.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    menuVerContactoActionPerformed(evt);
   }
  });
  menuAgregarContacto.add(menuVerContacto);

  jMenuBar1.add(menuAgregarContacto);

  jMenu2.setText("Notas");

  menuAgregarNotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
  menuAgregarNotas.setText("Agregar Nota");
  menuAgregarNotas.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    menuAgregarNotasActionPerformed(evt);
   }
  });
  jMenu2.add(menuAgregarNotas);

  menuVernotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
  menuVernotas.setText("Ver Notas");
  menuVernotas.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    menuVernotasActionPerformed(evt);
   }
  });
  jMenu2.add(menuVernotas);

  jMenuBar1.add(jMenu2);

  MenuCerrar.setText("Cerrar,,,");

  MenuSesion.setText("Cerrar sesión");
  MenuSesion.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    MenuSesionActionPerformed(evt);
   }
  });
  MenuCerrar.add(MenuSesion);

  MenuSalir.setText("Salir del sistema");
  MenuSalir.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    MenuSalirActionPerformed(evt);
   }
  });
  MenuCerrar.add(MenuSalir);

  jMenuBar1.add(MenuCerrar);

  setJMenuBar(jMenuBar1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(17, 17, 17)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
     .addGroup(layout.createSequentialGroup()
      .addGap(3, 3, 3)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
     .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
      .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(4, 4, 4)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
       .addComponent(btnContactos))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(19, 19, 19))
       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    .addGap(34, 34, 34))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(18, 18, 18)
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(12, 12, 12)
    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(layout.createSequentialGroup()
      .addGap(8, 8, 8)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(8, 8, 8)
        .addComponent(btnContactos))
       .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(8, 8, 8)
        .addComponent(btnNotas)))))
    .addContainerGap(21, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void menuVerContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerContactoActionPerformed
  FrmContactos contactos = new FrmContactos(this, true, id_global);
  contactos.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_menuVerContactoActionPerformed

 private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  FrmContactos contactos = new FrmContactos(this, true, id_global);
  contactos.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_jMenuItem1ActionPerformed

 private void MenuSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSesionActionPerformed
  FrmLogin login = new FrmLogin();
  login.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_MenuSesionActionPerformed

 private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
  // Cerramos el sistema por completo
  System.exit(0);
 }//GEN-LAST:event_MenuSalirActionPerformed

 private void menuAgregarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarNotasActionPerformed
  FrmNotas notas = new FrmNotas(this, true, id_global);
  notas.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_menuAgregarNotasActionPerformed

 private void menuVernotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVernotasActionPerformed
  FrmNotas notas = new FrmNotas(this, true, id_global);
  notas.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_menuVernotasActionPerformed

 private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
  FrmContactos contactos = new FrmContactos(this, true, id_global);
  contactos.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_btnContactosActionPerformed

 private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
  FrmNotas notas = new FrmNotas(this, true, id_global);
  notas.setVisible(true);

  this.dispose();
 }//GEN-LAST:event_btnNotasActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JMenu MenuCerrar;
 private javax.swing.JMenuItem MenuSalir;
 private javax.swing.JMenuItem MenuSesion;
 private javax.swing.JButton btnContactos;
 private javax.swing.JButton btnNotas;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JMenu jMenu2;
 private javax.swing.JMenuBar jMenuBar1;
 private javax.swing.JMenuItem jMenuItem1;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JPanel jPanel2;
 private javax.swing.JPanel jPanel3;
 private javax.swing.JPanel jPanel4;
 private javax.swing.JLabel lblBienvenida;
 private javax.swing.JLabel lblCarnet;
 private javax.swing.JLabel lblCarrera;
 private javax.swing.JLabel lblContactos;
 private javax.swing.JLabel lblEmail;
 private javax.swing.JLabel lblNombreCompleto;
 private javax.swing.JLabel lblNotas;
 private javax.swing.JMenu menuAgregarContacto;
 private javax.swing.JMenuItem menuAgregarNotas;
 private javax.swing.JMenuItem menuVerContacto;
 private javax.swing.JMenuItem menuVernotas;
 // End of variables declaration//GEN-END:variables

 private void actualizarBienvenida(int id) {
  // Objeto para la clase de conexion
  Conexion conn = new Conexion();

  try
  {
   String SQL = "CALL PA_buscar_alumnos(?)";
   PreparedStatement sentencia = conn.getConexion().prepareStatement(SQL);
   sentencia.setInt(1, id);

   ResultSet rs = sentencia.executeQuery();
   rs.next();
   String bienvenida = "<html><body><center>Hola " + rs.getString("nombre") + ", Bienvenido a tu centro <br> de contactos y notas<br>institucionales</center></body></html>";
   lblBienvenida.setText(bienvenida);

   lblCarnet.setText(rs.getString("carnet"));
   lblNombreCompleto.setText(rs.getString("nombre") + " " + rs.getString("apellido"));
   lblCarrera.setText(rs.getString("carrera"));
   lblEmail.setText(rs.getString("email"));

   rs.close();

   sentencia.close();
   conn.getConexion().close();
  } catch (Exception e)
  {
   System.out.println("Error | + info: " + e.getMessage());
  }

 }

 private void actualizarEstadisticas(int id) {
  // Objeto para la clase de conexion
  Conexion conn = new Conexion();

  try
  {
   String SQL = "";
   PreparedStatement sentencia;
   ResultSet rs;

   // Acutalizar el numero de contactos
   SQL = "CALL PA_cantidad_contactos(?)";
   sentencia = conn.getConexion().prepareStatement(SQL);
   sentencia.setInt(1, id);

   rs = sentencia.executeQuery();
   rs.next();
   lblContactos.setText(rs.getString("cantidad_contactos"));

   // Actualizar el numero de notas
   SQL = "CALL PA_cantidad_notas(?)";
   sentencia = conn.getConexion().prepareStatement(SQL);
   sentencia.setInt(1, id);

   rs = sentencia.executeQuery();
   rs.next();
   lblNotas.setText(rs.getString("cantidad_notas"));

   rs.close();

   sentencia.close();
   conn.getConexion().close();
  } catch (Exception e)
  {
   System.out.println("Error | + info: " + e.getMessage());
  }

 }
 
}
